language: python
cache: pip

install:
    - pip install -U lektor ghp-import
#    - pip install 'Werkzeug==0.16.1'  # https://github.com/lektor/lektor/issues/721
    - pip install 'Werkzeug==2.0.1'  # https://github.com/lektor/lektor/issues/721
script:
    - lektor build --output-path /tmp/lektor/
